<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <Target Name="CopyPhotoshopApiNativeLibrary" 
          AfterTargets="Build" Condition="Exists('$(MSBuildThisFileDirectory)..\bin-int\PhotoshopAPI\$(Configuration)\PhotoshopAPI.C\PhotoshopAPI.C.dll')">
    <Copy SourceFiles="$(MSBuildThisFileDirectory)..\bin-int\PhotoshopAPI\$(Configuration)\PhotoshopAPI.C\PhotoshopAPI.C.dll" DestinationFolder="$(OutputPath)runtimes\win-x64\native" />
  </Target>

</Project>
